env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
    - RUST_STABLE=1.29.1
os:
  - linux
  - osx
language: rust
rust:
  - 1.29.1
sudo: false
branches:
  only:
    - master
cache:
  cargo: true
  directories:
    - $HOME/elfutils
before_script:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/travis/cargo_install.sh > cargo_install.sh
  - bash cargo_install.sh cargo-prune
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview
script:
  - set -x;
    cargo test --release --verbose &&
    cargo fmt -- --check &&
    cargo clippy && cargo clippy --profile=test
before_cache:
  - cargo prune
