[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Return interface IP addresses on Posix and windows systems"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "get_if_addrs"
readme = "README.md"
repository = "https://github.com/maidsafe/get_if_addrs"
version = "0.1.1"

[dependencies]
ip = "~1.1.0"
libc = "~0.1.12"
log = "~0.3.4"
net2 = "0.2.20"
