[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Return interface IP addresses on Posix and windows systems"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "get_if_addrs"
readme = "README.md"
repository = "https://github.com/maidsafe/get_if_addrs"
version = "0.3.1"

[dependencies]
clippy = {version = "~0.0.37", optional = true}
libc = "~0.1.12"
c_linked_list = "~0.1.0"

